$bg_color = rgba({{ colors.background.dark.red }}, {{ colors.background.dark.green }}, {{ colors.background.dark.blue }}, 0.85)
$fg_color = rgba(190, 220, 250, 0.75)
$border_color = {{ colors.primary.dark.rgba }}
$in_color = rgba({{ colors.source_color.dark.red }}, {{ colors.source_color.dark.green }},{{ colors.source_color.dark.blue }}, 1)

