################################
#Mi configuracion de hyprlan :D#
################################


# Monitores
source=hyprland/monitors.conf


# Programas de inicio
source=hyprland/autostart.conf


# variables de entorno
source=hyprland/env.conf


# Permisos
source=hyprland/permissions.conf


# Estilos y sensaciones
source=hyprland/feeling.conf


# Animaciones
source=hyprland/animations.conf


# workspaces y ventanas
source=hyprland/workspaces.conf


# Dispositivos de entrada
source=hyprland/input.conf


# Atajos de teclado
source=hyprland/keybinds.conf


# Animaciones
source=hyprland/animations.conf
