-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "desc:Najing CEC Panda FPD Technology CO. ltd 0x004D",
  mode = "1920x1080@144",
  position = "0x0",
  scale = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
