animations {
	enabled = true

	# Movimientos
	bezier = entrada, 1, 0.2, 0.2, 0.5
	bezier = explosion, 0.5, -1, 0.2, 1
	bezier = rebote, 0, -0.5, 0, 2
	bezier = iman, 0.6, 0, 1, 0.7

	# Animaciones
	animation = windowsIn, 1, 6, rebote, slide
	animation = windowsOut, 1, 5, explosion, popin
	animation = windowsMove, 1, 4, iman

	animation = layersIn, 1, 4, explosion, popin left
	animation = layersOut, 1, 4, entrada, fadeOut

	animation = workspacesIn, 1, 3, iman, slidefade
	animation = workspacesOut, 1, 3, iman, slidefade

}

