###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
exec-once = swaync
exec-once = waybar > /dev/null 2>&1 &
exec-once = nm-applet
exec-once = awww-daemon
exec-once = ~/.config/Scrips/ranwall.sh		#cambio de wallpaper cada 5mins
exec-once = gsd-xsettings
exec-once = hyprctl setcursor Aemeath_Full 24
#exec-once = kitty tty-clock -tcs -C 5 & kitty
exec-once = qs -c overview  
exec-once = poweralertd &
