###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
exec-once = swaync
exec-once = waybar
exec-once = nm-applet
exec-once = awww-daemon
exec-once = ~/.config/Scrips/wallpaper_changer.sh
exec-once = gsd-xsettings
exec-once = hyprctl setcursor Aemeath_Full 24
exec-once = kitty tty-clock -tcs -C 5 & kitty 
