##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}


# reglas para waypaper 
windowrule = float on, match:class waypaper
windowrule = size 900 450, center on, match:class waypaper

windowrule = float on, match:class blueberry.py

windowrule = float on, match:class org.pulseaudio.pavucontrol
windowrule = size 900 450, center on, match:class org.pulseaudio.pavucontrol

windowrule = float on, match:class nwg-look
windowrule = size 900 450, center on, match:class nwg-look

windowrule = float on, match:class org.gnome.Loupe
windowrule = size 960 540, float on, match:class mpv 

windowrule = float on, match:title Actualización del Sistema
windowrule = size 400 500, match:title Actualizacion del Sistema
