[config.wallpaper]
command = "awww"
arguments = ["img", "--transition-type", "center"]
set = false

[templates.cava]
input_path = '~/.config/matugen/templates/cava.ini'
output_path = '~/.config/cava/config'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -R -rs'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/current-theme.config'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetify.ini'
output_path = '~/.config/matugen/colors/spicetify.ini'

[templates.sway]
input_path = '~/.config/matugen/templates/sway.conf'
output_path = '~/.config/matugen/colors/sway.conf'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/theme.rasi'

