[config.wallpaper]
command = "awww"
arguments = ["img", "--transition-type", "center"]
set = false

[templates.cava]
input_path = '~/.config/matugen/templates/cava.ini'
output_path = '~/.config/cava/config'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -R -rs'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/theme.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill waybar && waybar > /dev/null 2>&1 &'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetify.ini'
output_path = '~/.config/matugen/colors/spicetify.ini'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/current-theme.conf'
post_hook = 'killall -USR1 kitty'

[templates.wallselector]
input_path = '~/.config/matugen/templates/wall_selector.json'
output_path = '~/.config/quickshell/wallpaper_select/config.json'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock/colors.conf'
